name: 'Breadcrumbs Visibility'
type: module
description: Regulate the breadcrumbs display for node entities.
core_version_requirement: ^9.1 || ^10
dependencies:
  - drupal:block
  - drupal:node
  - drupal:system

# Information added by Drupal.org packaging script on 2022-08-03
version: '8.x-1.3'
project: 'breadcrumbs_visibility'
datestamp: 1659549946
